betas:
  value: !!python/tuple
  - 0.9
  - 0.99
data:
  value:
    add_cycles_feat: true
    add_path_feat: true
    add_random_feat: true
    add_spectral_feat: true
    data: community
    dir: ./data
    max_feat_num: 0
    max_node_num: 20
    min_node_num: 12
    test_split: 0.2
dataset:
  value: community
device:
  value: cuda:3
exp_name:
  value: nar_fix_loss
gpu:
  value: '3'
iterations_rate:
  value: 0.5
log:
  value:
    debug: false
    n_loggin_epochs: 100
    n_loggin_steps: 1000
    wandb: online
mask_func:
  value: cosine
model:
  value:
    decoder:
      mlp_hidden_size: 64
      mlp_n_layers: 3
      n_layers: 2
      name: GNN
      nhf: 32
      normalization: batch_norm
      skip_connection: true
    encoder:
      mlp_hidden_size: 64
      mlp_n_layers: 3
      n_layers: 2
      name: GNN_PYG
      nhf: 32
      normalization: batch_norm
      skip_connection: true
    gamma: 0.1
    quantizer:
      codebook_size: 128
      commitment_cost: 0.25
      decay: 0.99
      epsilon: 1e-05
      init_steps: 0
      name: Quantizer
      nc: 1
      nz: 8
n_samples:
  value: 20
run_name:
  value: community_128_1_cosine_0.5
sample:
  value: true
train_prior:
  value: true
training:
  value:
    batch_size: 32
    beta1: 0.9
    beta2: 0.99
    betas: !!python/tuple
    - 0.9
    - 0.99
    decay_iteration: 10000
    epochs: 2500
    learning_rate: 0.001
    lr_decay: 0.5
    n_iter: 1000000
    sort_codebook: false
    sort_indices: false
transformer:
  value:
    d_model: 64
    n_blocks: 3
    num_heads: 16
use_mask:
  value: true
work_type:
  value: sample
