wandb_version: 1

log:
  desc: null
  value:
    n_loggin_steps: 2000
    n_loggin_epochs: 1
    wandb: online
    debug: false
data:
  desc: null
  value:
    dir: ./data
    data: ZINC250k
    max_feat_num: 9
    max_node_num: 38
    add_path_feat: true
    add_cycles_feat: true
    add_random_feat: true
    add_spectral_feat: true
model:
  desc: null
  value:
    gamma: 0.1
    decoder:
      nhf: 32
      name: GNN
      n_layers: 4
      mlp_n_layers: 3
      normalization: batch_norm
      mlp_hidden_size: 128
      skip_connection: true
    encoder:
      nhf: 32
      name: GNN_PYG
      n_layers: 4
      mlp_n_layers: 3
      normalization: batch_norm
      add_input_noise: false
      mlp_hidden_size: 128
      skip_connection: true
    quantizer:
      nc: 2
      nz: 8
      name: Quantizer
      decay: 0.99
      epsilon: 1.0e-05
      codebook_size: 32
      commitment_cost: 0.25
      init_steps: 0
sample:
  desc: null
  value: false
dataset:
  desc: null
  value: zinc
training:
  desc: null
  value:
    batch_size: 32
    learning_rate: 0.0005
    lr_decay: 0.5
    decay_iteration: 25000
    beta1: 0.9
    beta2: 0.99
    n_iter: 1000000
    epochs: 40
    sort_indices: true
    betas:
    - 0.9
    - 0.99
work_type:
  desc: null
  value: train_prior
train_prior:
  desc: null
  value: true
model_folder:
  desc: null
  value: run-20230712_112605-chfc1oz3
transformer:
  desc: null
  value:
    d_model: 256
    num_heads: 16
    n_blocks: 6
autoencoder_path:
  desc: null
  value: run-20230712_112605-chfc1oz3
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691834392.208897
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      3:
      - 3
      - 16
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
