data:
  value:
    add_cycles_feat: true
    add_path_feat: true
    add_random_feat: true
    add_spectral_feat: true
    batch_size: 16
    data: grid
    dir: ./data
    max_feat_num: 0
    max_node_num: 361
    min_node_num: 12
    test_split: 0.2
dataset:
  value: grid
device:
  value: cuda:3
exp_name:
  value: ar_baseline
gpu:
  value: '3'
log:
  value:
    debug: false
    n_loggin_epochs: 100
    n_loggin_steps: 1000
    wandb: online
model:
  value:
    decoder:
      mlp_hidden_size: 256
      mlp_n_layers: 3
      n_layers: 8
      name: GNN
      nhf: 64
      normalization: batch_norm
      skip_connection: true
    encoder:
      mlp_hidden_size: 256
      mlp_n_layers: 3
      n_layers: 8
      name: GNN_PYG
      nhf: 64
      normalization: batch_norm
      skip_connection: true
    gamma: 0.1
    quantizer:
      codebook_size: 1024
      commitment_cost: 0.25
      decay: 0.99
      epsilon: 1.0e-05
      init_steps: 0
      name: Quantizer
      nc: 1
      nz: 8
run_name:
  value: grid_1024_1
sample:
  value: false
train_prior:
  value: false
training:
  value:
    batch_size: 16
    beta1: 0.9
    beta2: 0.99
    betas: !!python/tuple
    - 0.9
    - 0.99
    decay_iteration: 5000
    epochs: 10000
    learning_rate: 0.0003
    log: false
    lr_decay: 0.5
    n_iter: 100000
work_type:
  value: train_autoencoder
