betas:
  value: !!python/tuple
  - 0.9
  - 0.999
data:
  value:
    add_cycles_feat: true
    add_path_feat: true
    add_random_feat: true
    add_spectral_feat: true
    data: planar
    dir: ./data
    max_feat_num: 0
    max_node_num: 64
    min_node_num: 64
    test_split: 0.2
dataset:
  value: planar
device:
  value: cuda:3
exp_name:
  value: ar_baseline
gpu:
  value: '3'
log:
  value:
    debug: false
    n_loggin_epochs: 100
    n_loggin_steps: 1000
    wandb: false
model:
  value:
    decoder:
      mlp_hidden_size: 128
      mlp_n_layers: 3
      n_layers: 6
      name: GNN
      nhf: 32
      normalization: batch_norm
      skip_connection: true
    encoder:
      mlp_hidden_size: 128
      mlp_n_layers: 3
      n_layers: 6
      name: GNN_PYG
      nhf: 32
      normalization: batch_norm
      skip_connection: true
    gamma: 0.1
    quantizer:
      codebook_size: 512
      commitment_cost: 0.25
      decay: 0.99
      epsilon: 1.0e-05
      init_steps: 0
      name: Quantizer
      nc: 1
      nz: 8
n_samples:
  value: 10000
run_name:
  value: planar_512_1_large
sample:
  value: true
train_prior:
  value: true
training:
  value:
    batch_size: 64
    beta1: 0.9
    beta2: 0.999
    betas: !!python/tuple
    - 0.9
    - 0.999
    decay_iteration: 1500
    epochs: 1500
    learning_rate: 0.0003
    lr_decay: 0.7
    n_iter: 500000
    sort_codebook: false
    sort_indices: true
transformer:
  value:
    d_model: 128
    n_blocks: 4
    num_heads: 8
work_type:
  value: sample
