data:
  value:
    add_cycles_feat: true
    add_path_feat: true
    add_random_feat: true
    add_spectral_feat: true
    data: proteins
    dir: ./data
    max_feat_num: 0
    max_node_num: 1396
    min_node_num: 30
    test_split: 0.2
dataset:
  value: proteins_full
device:
  value: cuda:1
exp_name:
  value: icdm_plot
gpu:
  value: '1'
iterations_rate:
  value: 1
log:
  value:
    debug: false
    n_loggin_epochs: 100
    n_loggin_steps: 1000
    wandb: disabled
mask_func:
  value: linear
model:
  value:
    decoder:
      mlp_hidden_size: 2
      mlp_n_layers: 3
      n_layers: 3
      name: GNN
      nhf: 2
      normalization: batch_norm
      skip_connection: true
    encoder:
      mlp_hidden_size: 2
      mlp_n_layers: 3
      n_layers: 3
      name: GNN_PYG
      nhf: 2
      normalization: batch_norm
      skip_connection: true
    gamma: 0.1
    quantizer:
      codebook_size: 2048
      commitment_cost: 0.25
      decay: 0.99
      epsilon: 1.0e-05
      init_steps: 100
      name: Quantizer
      nc: 2
      nz: 8
run_name:
  value: proteins_full_cb2048_2
sample:
  value: false
train_prior:
  value: false
training:
  value:
    batch_size: 1
    beta1: 0.9
    beta2: 0.99
    betas: !!python/tuple
    - 0.9
    - 0.99
    decay_iteration: 10000
    epochs: 20000
    learning_rate: 0.001
    log: false
    lr_decay: 0.5
    n_iter: 1000000
use_mask:
  value: false
work_type:
  value: train_autoencoder
