data:
  value:
    add_cycles_feat: true
    add_path_feat: true
    add_random_feat: true
    add_spectral_feat: true
    data: gnp
    dir: ./data
    max_feat_num: 0
    max_node_num: 96
    min_node_num: 12
    test_split: 0.2
dataset:
  value: gnp
device:
  value: cuda:2
exp_name:
  value: icdm
gpu:
  value: '2'
iterations_rate:
  value: 1
log:
  value:
    debug: false
    n_loggin_epochs: 1
    n_loggin_steps: 100
    wandb: disabled
mask_func:
  value: linear
model:
  value:
    decoder:
      mlp_hidden_size: 128
      mlp_n_layers: 3
      n_layers: 6
      name: GNN
      nhf: 32
      normalization: batch_norm
      skip_connection: true
    encoder:
      mlp_hidden_size: 128
      mlp_n_layers: 3
      n_layers: 6
      name: GNN_PYG
      nhf: 32
      normalization: batch_norm
      skip_connection: true
    gamma: 0.1
    quantizer:
      codebook_size: 512
      commitment_cost: 0.25
      decay: 0.99
      epsilon: 1.0e-05
      init_steps: 0
      name: Quantizer
      nc: 1
      nz: 8
run_name:
  value: gnp_512_1_cosine_1
sample:
  value: false
train_prior:
  value: false
training:
  value:
    batch_size: 16
    beta1: 0.9
    beta2: 0.99
    betas: !!python/tuple
    - 0.9
    - 0.99
    decay_iteration: 10000
    epochs: 10000
    learning_rate: 0.0005
    log: false
    lr_decay: 0.5
    n_iter: 100000
use_mask:
  value: false
work_type:
  value: train_autoencoder
